# Generated by Django 5.0 on 2023-12-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_home_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
