# Generated by Django 5.0 on 2023-12-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_home_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Post',
        ),
    ]
